import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-a',
  templateUrl: './a.component.html',
  styleUrls: ['./a.component.scss'],
})
export class AComponent implements OnInit {
  data = {
    fields4: [
      '報酬指數',
      '收盤指數',
      '漲跌(+/-) ',
      '漲跌點數',
      '漲跌百分比(%)',
      '特殊處理註記',
    ],
    fields6: [
      '報酬指數 ',
      '收盤指數',
      '漲跌(+/-)',
      '漲跌點數',
      '漲跌百分比(%)',
      '特殊處理註記 ',
    ],
    data6: [
      [
        '漲升股利150報酬指數',
        '7,111.49',
        "<p style ='color:red'>+</p>",
        '75.01',
        '1.07',
        null,
      ],
      [
        '漲升股利100報酬指數',
        '7,108.18',
        "<p style ='color:red'>+</p>",
        '67.38',
        '0.96',
        null,
      ],
      [
        '藍籌30報酬指數',
        '6,306.22',
        "<p style ='color:red'>+</p>",
        '61.55',
        '0.99',
        null,
      ],
      [
        '工業菁英30報酬指數',
        '6,682.46',
        "<p style ='color:red'>+</p>",
        '68.84',
        '1.04',
        null,
      ],
      [
        '電子菁英30報酬指數',
        '6,496.00',
        "<p style ='color:red'>+</p>",
        '54.50',
        '0.85',
        null,
      ],
      [
        '低波動股利精選30報酬指數',
        '6,674.19',
        "<p style ='color:red'>+</p>",
        '36.67',
        '0.55',
        null,
      ],
      [
        '低貝塔100報酬指數',
        '6,559.09',
        "<p style ='color:red'>+</p>",
        '25.50',
        '0.39',
        null,
      ],
      [
        '中小型精選50報酬指數',
        '6,791.09',
        "<p style ='color:red'>+</p>",
        '33.33',
        '0.49',
        null,
      ],
      [
        '中小型A級動能50報酬指數',
        '7,204.10',
        "<p style ='color:red'>+</p>",
        '79.54',
        '1.12',
        null,
      ],
      [
        '特選高息低波報酬指數',
        '6,074.54',
        "<p style ='color:red'>+</p>",
        '26.87',
        '0.44',
        null,
      ],
      [
        '臺灣永續報酬指數',
        '5,839.76',
        "<p style ='color:red'>+</p>",
        '54.71',
        '0.95',
        null,
      ],
      [
        '特選內需高收益報酬指數',
        '6,102.19',
        "<p style ='color:red'>+</p>",
        '40.42',
        '0.67',
        null,
      ],
      [
        '價值投資報酬指數',
        '6,232.57',
        "<p style ='color:red'>+</p>",
        '25.06',
        '0.40',
        null,
      ],
      [
        '存股雙十等權重報酬指數',
        '5,281.02',
        "<p style ='color:red'>+</p>",
        '54.57',
        '1.04',
        null,
      ],
      [
        '特選大蘋果報酬指數',
        '5,428.16',
        "<p style ='color:red'>+</p>",
        '64.99',
        '1.21',
        null,
      ],
      [
        '中小型300報酬指數',
        '5,972.08',
        "<p style ='color:red'>+</p>",
        '49.27',
        '0.83',
        null,
      ],
      [
        '特股高息20報酬指數',
        '5,381.28',
        "<p style ='color:red'>+</p>",
        '20.22',
        '0.38',
        null,
      ],
      [
        '臺灣500報酬指數',
        '5,679.12',
        "<p style ='color:red'>+</p>",
        '53.49',
        '0.95',
        null,
      ],
      [
        '特選外資豐擁50報酬指數',
        '5,611.93',
        "<p style ='color:red'>+</p>",
        '53.97',
        '0.97',
        null,
      ],
      [
        '臺灣勞工權益報酬指數',
        '5,316.04',
        "<p style ='color:red'>+</p>",
        '50.20',
        '0.95',
        null,
      ],
    ],
    data4: [
      [
        '寶島股價報酬指數',
        '15,298.66',
        "<p style ='color:red'>+</p>",
        '140.03',
        '0.92',
        null,
      ],
      [
        '發行量加權股價報酬指數',
        '19,790.44',
        "<p style ='color:red'>+</p>",
        '184.48',
        '0.94',
        null,
      ],
      [
        '臺灣公司治理100報酬指數',
        '7,357.75',
        "<p style ='color:red'>+</p>",
        '69.45',
        '0.95',
        null,
      ],
      [
        '臺灣50報酬指數',
        '14,975.22',
        "<p style ='color:red'>+</p>",
        '151.06',
        '1.02',
        null,
      ],
      [
        '臺灣中型100報酬指數',
        '13,919.56',
        "<p style ='color:red'>+</p>",
        '115.02',
        '0.83',
        null,
      ],
      [
        '臺灣資訊科技報酬指數',
        '19,142.00',
        "<p style ='color:red'>+</p>",
        '245.20',
        '1.30',
        null,
      ],
      [
        '臺灣發達報酬指數',
        '13,569.48',
        "<p style ='color:red'>+</p>",
        '116.84',
        '0.87',
        null,
      ],
      [
        '臺灣高股息報酬指數',
        '13,621.30',
        "<p style ='color:red'>+</p>",
        '93.12',
        '0.69',
        null,
      ],
      [
        '臺灣就業99報酬指數',
        '8,645.58',
        "<p style ='color:red'>+</p>",
        '88.24',
        '1.03',
        null,
      ],
      [
        '臺灣高薪100報酬指數',
        '7,342.77',
        "<p style ='color:red'>+</p>",
        '63.20',
        '0.87',
        null,
      ],
      [
        '未含金融電子報酬指數',
        '22,668.65',
        "<p style ='color:red'>+</p>",
        '181.83',
        '0.81',
        null,
      ],
      [
        '小型股300報酬指數',
        '7,646.26',
        "<p style ='color:red'>+</p>",
        '58.38',
        '0.77',
        null,
      ],
      [
        '水泥類報酬指數',
        '259.31',
        "<p style ='color:green'>-</p>",
        '0.07',
        '-0.03',
        null,
      ],
      [
        '食品類報酬指數',
        '2,515.20',
        "<p style ='color:red'>+</p>",
        '22.00',
        '0.88',
        null,
      ],
      [
        '塑膠類報酬指數',
        '394.97',
        "<p style ='color:red'>+</p>",
        '4.52',
        '1.16',
        null,
      ],
      [
        '紡織纖維類報酬指數',
        '780.99',
        "<p style ='color:red'>+</p>",
        '7.17',
        '0.93',
        null,
      ],
      [
        '電機機械類報酬指數',
        '229.53',
        "<p style ='color:red'>+</p>",
        '0.43',
        '0.19',
        null,
      ],
      [
        '電器電纜類報酬指數',
        '60.92',
        "<p style ='color:green'>-</p>",
        '0.04',
        '-0.07',
        null,
      ],
      [
        '化學生技醫療類報酬指數',
        '140.73',
        "<p style ='color:red'>+</p>",
        '0.53',
        '0.38',
        null,
      ],
      [
        '化學類報酬指數',
        '156.57',
        "<p style ='color:red'>+</p>",
        '0.68',
        '0.44',
        null,
      ],
      [
        '生技醫療類報酬指數',
        '84.07',
        "<p style ='color:red'>+</p>",
        '0.26',
        '0.31',
        null,
      ],
      [
        '玻璃陶瓷類報酬指數',
        '37.96',
        "<p style ='color:red'>+</p>",
        '0.85',
        '2.29',
        null,
      ],
      [
        '造紙類報酬指數',
        '257.30',
        "<p style ='color:red'>+</p>",
        '0.61',
        '0.24',
        null,
      ],
      [
        '鋼鐵類報酬指數',
        '150.47',
        "<p style ='color:red'>+</p>",
        '0.18',
        '0.12',
        null,
      ],
      [
        '橡膠類報酬指數',
        '380.61',
        "<p style ='color:red'>+</p>",
        '2.36',
        '0.62',
        null,
      ],
      [
        '汽車類報酬指數',
        '412.86',
        "<p style ='color:red'>+</p>",
        '8.62',
        '2.13',
        null,
      ],
      [
        '電子工業類報酬指數',
        '753.75',
        "<p style ='color:red'>+</p>",
        '8.42',
        '1.13',
        null,
      ],
      [
        '半導體類報酬指數',
        '287.50',
        "<p style ='color:red'>+</p>",
        '3.81',
        '1.34',
        null,
      ],
      [
        '電腦及週邊設備類報酬指數',
        '173.70',
        "<p style ='color:red'>+</p>",
        '1.80',
        '1.05',
        null,
      ],
      [
        '光電類報酬指數',
        '49.04',
        "<p style ='color:red'>+</p>",
        '0.52',
        '1.07',
        null,
      ],
      [
        '通信網路類報酬指數',
        '238.56',
        "<p style ='color:red'>+</p>",
        '1.35',
        '0.57',
        null,
      ],
      [
        '電子零組件類報酬指數',
        '175.54',
        "<p style ='color:red'>+</p>",
        '1.12',
        '0.64',
        null,
      ],
      [
        '電子通路類報酬指數',
        '225.67',
        "<p style ='color:red'>+</p>",
        '1.20',
        '0.53',
        null,
      ],
      [
        '資訊服務類報酬指數',
        '235.67',
        "<p style ='color:red'>+</p>",
        '1.86',
        '0.80',
        null,
      ],
      [
        '其他電子類報酬指數',
        '107.15',
        "<p style ='color:red'>+</p>",
        '1.39',
        '1.31',
        null,
      ],
      [
        '建材營造類報酬指數',
        '487.78',
        "<p style ='color:red'>+</p>",
        '5.92',
        '1.23',
        null,
      ],
      [
        '航運類報酬指數',
        '91.13',
        "<p style ='color:red'>+</p>",
        '0.24',
        '0.26',
        null,
      ],
      [
        '觀光類報酬指數',
        '128.75',
        "<p style ='color:green'>-</p>",
        '0.03',
        '-0.02',
        null,
      ],
      [
        '金融保險類報酬指數',
        '1,923.90',
        "<p style ='color:red'>+</p>",
        '9.86',
        '0.52',
        null,
      ],
      [
        '貿易百貨類報酬指數',
        '341.41',
        "<p style ='color:red'>+</p>",
        '5.52',
        '1.64',
        null,
      ],
      [
        '油電燃氣類報酬指數',
        '180.52',
        "<p style ='color:red'>+</p>",
        '1.25',
        '0.70',
        null,
      ],
      [
        '其他類報酬指數',
        '431.42',
        "<p style ='color:red'>+</p>",
        '2.64',
        '0.62',
        null,
      ],
    ],
    alignsStyle6: [
      ['center', 'center', 'center', 'center', 'center', 'center'],
      ['left', 'right', 'center', 'right', 'right', 'center'],
      [16, 8, 8, 4, 12, 4],
    ],
    subtitle4: '報酬指數(臺灣證券交易所)',
    data5: [
      [
        '臺灣生技報酬指數',
        '4,822.51',
        "<p style ='color:green'>-</p>",
        '28.18',
        '-0.58',
        null,
      ],
      [
        '臺灣中小型公司治理報酬指數',
        '6,098.65',
        "<p style ='color:red'>+</p>",
        '11.94',
        '0.20',
        null,
      ],
      [
        '臺灣IPO報酬指數',
        '5,650.08',
        "<p style ='color:red'>+</p>",
        '35.10',
        '0.63',
        null,
      ],
    ],
    subtitle7: '108年09月04日 大盤統計資訊',
    alignsStyle7: [
      ['center', 'center', 'center', 'center'],
      ['left', 'right', 'right', 'right'],
      [16, 8, 8, 6],
    ],
    alignsStyle1: [
      ['center', 'center', 'center', 'center', 'center', 'center'],
      ['left', 'right', 'center', 'right', 'right', 'center'],
      [16, 8, 8, 4, 12, 4],
    ],
    notes9: [
      '漲跌(+/-)欄位符號說明:+/-/X表示漲/跌/不比價。',
      '當證券代號為認購(售)權證及認股權憑證時本益比欄位置為結算價；但如為以外國證券或指數為標的之認購(售)權證及履約方式採歐式者，該欄位為空白。',
      '除境外指數股票型基金及外國股票第二上市外，餘交易單位皆為千股。',
      '本統計資訊含一般、零股、盤後定價、鉅額交易，不含拍賣、標購。',
    ],
    subtitle6: '報酬指數(臺灣指數公司)',
    subtitle3: '價格指數(臺灣指數公司)',
    alignsStyle2: [
      ['center', 'center', 'center', 'center', 'center', 'center'],
      ['left', 'right', 'center', 'right', 'right', 'center'],
      [16, 8, 8, 4, 12, 4],
    ],
    data3: [
      [
        '金融類日報酬兩倍指數',
        '19,369.14',
        "<p style ='color:red'>+</p>",
        '196.00',
        '1.02',
        null,
      ],
      [
        '金融類日報酬反向一倍指數',
        '6,676.78',
        "<p style ='color:green'>-</p>",
        '34.30',
        '-0.51',
        null,
      ],
      [
        '漲升股利150指數',
        '6,026.78',
        "<p style ='color:red'>+</p>",
        '63.58',
        '1.07',
        null,
      ],
      [
        '漲升股利100指數',
        '6,006.56',
        "<p style ='color:red'>+</p>",
        '56.94',
        '0.96',
        null,
      ],
      [
        '藍籌30指數',
        '5,574.66',
        "<p style ='color:red'>+</p>",
        '54.41',
        '0.99',
        null,
      ],
      [
        '工業菁英30指數',
        '5,905.04',
        "<p style ='color:red'>+</p>",
        '60.83',
        '1.04',
        null,
      ],
      [
        '電子菁英30指數',
        '5,802.14',
        "<p style ='color:red'>+</p>",
        '48.68',
        '0.85',
        null,
      ],
      [
        '低波動股利精選30指數',
        '5,846.26',
        "<p style ='color:red'>+</p>",
        '32.13',
        '0.55',
        null,
      ],
      [
        '低貝塔100指數',
        '5,763.69',
        "<p style ='color:red'>+</p>",
        '22.32',
        '0.39',
        null,
      ],
      [
        '藍籌30反向一倍指數',
        '8,560.74',
        "<p style ='color:green'>-</p>",
        '85.22',
        '-0.99',
        null,
      ],
      [
        '中小型精選50指數',
        '5,899.26',
        "<p style ='color:red'>+</p>",
        '28.55',
        '0.49',
        null,
      ],
      [
        '中小型A級動能50指數',
        '6,626.78',
        "<p style ='color:red'>+</p>",
        '73.17',
        '1.12',
        null,
      ],
      [
        '特選高息低波指數',
        '5,231.20',
        "<p style ='color:red'>+</p>",
        '23.14',
        '0.44',
        null,
      ],
      [
        '臺灣永續指數',
        '5,177.29',
        "<p style ='color:red'>+</p>",
        '48.50',
        '0.95',
        null,
      ],
      [
        '工業菁英30反向一倍指數',
        '9,365.53',
        "<p style ='color:green'>-</p>",
        '98.51',
        '-1.04',
        null,
      ],
      [
        '特選內需高收益指數',
        '5,483.26',
        "<p style ='color:red'>+</p>",
        '36.32',
        '0.67',
        null,
      ],
      [
        '價值投資指數',
        '5,495.58',
        "<p style ='color:red'>+</p>",
        '22.10',
        '0.40',
        null,
      ],
      [
        '中小型300指數',
        '5,741.89',
        "<p style ='color:red'>+</p>",
        '47.23',
        '0.83',
        null,
      ],
      [
        '臺灣勞工權益指數',
        '5,108.51',
        "<p style ='color:red'>+</p>",
        '48.24',
        '0.95',
        null,
      ],
    ],
    alignsStyle9: [
      [
        'center',
        'center',
        'center',
        'center',
        'center',
        'center',
        'center',
        'center',
        'center',
        'center',
        'center',
        'center',
        'center',
        'center',
        'center',
        'center',
        'center',
        'center',
      ],
      [
        'left',
        'center',
        'right',
        'right',
        'right',
        'right',
        'right',
        'right',
        'right',
        'center',
        'right',
        'right',
        'center',
        'right',
        'center',
        'right',
      ],
      [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
    ],
    data1: [
      [
        '寶島股價指數',
        '12,223.02',
        "<p style ='color:red'>+</p>",
        '111.57',
        '0.92',
        null,
      ],
      [
        '發行量加權股價指數',
        '10,657.31',
        "<p style ='color:red'>+</p>",
        '99.10',
        '0.94',
        null,
      ],
      [
        '臺灣公司治理100指數',
        '6,009.84',
        "<p style ='color:red'>+</p>",
        '56.73',
        '0.95',
        null,
      ],
      [
        '臺灣50指數',
        '7,979.16',
        "<p style ='color:red'>+</p>",
        '80.49',
        '1.02',
        null,
      ],
      [
        '臺灣中型100指數',
        '8,008.97',
        "<p style ='color:red'>+</p>",
        '66.18',
        '0.83',
        null,
      ],
      [
        '臺灣資訊科技指數',
        '10,795.86',
        "<p style ='color:red'>+</p>",
        '138.29',
        '1.30',
        null,
      ],
      [
        '臺灣發達指數',
        '7,997.37',
        "<p style ='color:red'>+</p>",
        '68.86',
        '0.87',
        null,
      ],
      [
        '臺灣高股息指數',
        '6,081.06',
        "<p style ='color:red'>+</p>",
        '41.58',
        '0.69',
        null,
      ],
      [
        '臺灣就業99指數',
        '6,265.52',
        "<p style ='color:red'>+</p>",
        '63.94',
        '1.03',
        null,
      ],
      [
        '臺灣高薪100指數',
        '5,869.03',
        "<p style ='color:red'>+</p>",
        '50.51',
        '0.87',
        null,
      ],
      [
        '未含金融指數',
        '8,972.22',
        "<p style ='color:red'>+</p>",
        '89.67',
        '1.01',
        null,
      ],
      [
        '未含電子指數',
        '14,412.38',
        "<p style ='color:red'>+</p>",
        '101.91',
        '0.71',
        null,
      ],
      [
        '未含金融電子指數',
        '12,049.11',
        "<p style ='color:red'>+</p>",
        '96.00',
        '0.80',
        null,
      ],
      [
        '小型股300指數',
        '6,496.84',
        "<p style ='color:red'>+</p>",
        '48.90',
        '0.76',
        null,
      ],
      [
        '水泥窯製類指數',
        '563.40',
        "<p style ='color:red'>+</p>",
        '1.17',
        '0.21',
        null,
      ],
      [
        '塑膠化工類指數',
        '820.63',
        "<p style ='color:red'>+</p>",
        '7.59',
        '0.93',
        null,
      ],
      [
        '機電類指數',
        '2,491.54',
        "<p style ='color:red'>+</p>",
        '27.06',
        '1.10',
        null,
      ],
      [
        '水泥類指數',
        '154.87',
        "<p style ='color:green'>-</p>",
        '0.04',
        '-0.03',
        null,
      ],
      [
        '食品類指數',
        '1,804.61',
        "<p style ='color:red'>+</p>",
        '15.18',
        '0.85',
        null,
      ],
      [
        '塑膠類指數',
        '250.60',
        "<p style ='color:red'>+</p>",
        '2.87',
        '1.16',
        null,
      ],
      [
        '紡織纖維類指數',
        '533.43',
        "<p style ='color:red'>+</p>",
        '4.90',
        '0.93',
        null,
      ],
      [
        '電機機械類指數',
        '162.91',
        "<p style ='color:red'>+</p>",
        '0.31',
        '0.19',
        null,
      ],
      [
        '電器電纜類指數',
        '44.95',
        "<p style ='color:green'>-</p>",
        '0.02',
        '-0.04',
        null,
      ],
      [
        '化學生技醫療類指數',
        '97.95',
        "<p style ='color:red'>+</p>",
        '0.34',
        '0.35',
        null,
      ],
      [
        '化學類指數',
        '103.33',
        "<p style ='color:red'>+</p>",
        '0.38',
        '0.37',
        null,
      ],
      [
        '生技醫療類指數',
        '63.80',
        "<p style ='color:red'>+</p>",
        '0.20',
        '0.31',
        null,
      ],
      [
        '玻璃陶瓷類指數',
        '33.18',
        "<p style ='color:red'>+</p>",
        '0.75',
        '2.31',
        null,
      ],
      [
        '造紙類指數',
        '184.68',
        "<p style ='color:red'>+</p>",
        '0.43',
        '0.23',
        null,
      ],
      [
        '鋼鐵類指數',
        '101.04',
        "<p style ='color:red'>+</p>",
        '0.12',
        '0.12',
        null,
      ],
      [
        '橡膠類指數',
        '261.59',
        "<p style ='color:red'>+</p>",
        '1.62',
        '0.62',
        null,
      ],
      [
        '汽車類指數',
        '284.69',
        "<p style ='color:red'>+</p>",
        '5.89',
        '2.11',
        null,
      ],
      [
        '電子工業類指數',
        '444.83',
        "<p style ='color:red'>+</p>",
        '4.97',
        '1.13',
        null,
      ],
      [
        '半導體類指數',
        '178.75',
        "<p style ='color:red'>+</p>",
        '2.37',
        '1.34',
        null,
      ],
      [
        '電腦及週邊設備類指數',
        '93.26',
        "<p style ='color:red'>+</p>",
        '0.96',
        '1.04',
        null,
      ],
      [
        '光電類指數',
        '36.52',
        "<p style ='color:red'>+</p>",
        '0.38',
        '1.05',
        null,
      ],
      [
        '通信網路類指數',
        '126.26',
        "<p style ='color:red'>+</p>",
        '0.72',
        '0.57',
        null,
      ],
      [
        '電子零組件類指數',
        '103.87',
        "<p style ='color:red'>+</p>",
        '0.66',
        '0.64',
        null,
      ],
      [
        '電子通路類指數',
        '113.75',
        "<p style ='color:red'>+</p>",
        '0.60',
        '0.53',
        null,
      ],
      [
        '資訊服務類指數',
        '119.09',
        "<p style ='color:red'>+</p>",
        '0.94',
        '0.80',
        null,
      ],
      [
        '其他電子類指數',
        '76.04',
        "<p style ='color:red'>+</p>",
        '0.99',
        '1.32',
        null,
      ],
      [
        '建材營造類指數',
        '287.34',
        "<p style ='color:red'>+</p>",
        '3.49',
        '1.23',
        null,
      ],
      [
        '航運類指數',
        '67.79',
        "<p style ='color:red'>+</p>",
        '0.18',
        '0.27',
        null,
      ],
      [
        '觀光類指數',
        '101.34',
        "<p style ='color:green'>-</p>",
        '0.02',
        '-0.02',
        null,
      ],
      [
        '金融保險類指數',
        '1,260.48',
        "<p style ='color:red'>+</p>",
        '6.41',
        '0.51',
        null,
      ],
      [
        '貿易百貨類指數',
        '239.11',
        "<p style ='color:red'>+</p>",
        '3.87',
        '1.65',
        null,
      ],
      [
        '油電燃氣類指數',
        '123.99',
        "<p style ='color:red'>+</p>",
        '0.85',
        '0.69',
        null,
      ],
      [
        '其他類指數',
        '280.23',
        "<p style ='color:red'>+</p>",
        '1.72',
        '0.62',
        null,
      ],
      [
        '臺指日報酬兩倍指數',
        '15,926.53',
        "<p style ='color:red'>+</p>",
        '293.47',
        '1.88',
        null,
      ],
      [
        '臺指反向一倍指數',
        '7,194.04',
        "<p style ='color:green'>-</p>",
        '68.16',
        '-0.94',
        null,
      ],
      [
        '電子類兩倍槓桿指數',
        '12,692.04',
        "<p style ='color:red'>+</p>",
        '280.48',
        '2.26',
        null,
      ],
      [
        '電子類反向指數',
        '7,530.20',
        "<p style ='color:green'>-</p>",
        '86.06',
        '-1.13',
        null,
      ],
    ],
    subtitle5: '報酬指數(跨市場)',
    subtitle9: '108年09月04日每日收盤行情(全部(不含權證、牛熊證))',
    subtitle8: '漲跌證券數合計',
    alignsStyle4: [
      ['center', 'center', 'center', 'center', 'center', 'center'],
      ['left', 'right', 'center', 'right', 'right', 'center'],
      [16, 8, 8, 4, 12, 4],
    ],
    subtitle1: '108年09月04日 價格指數(臺灣證券交易所)',
    notes8: [
      '"漲跌價差"為當日收盤價與前一日收盤價比較。',
      '"無比價"含前一日無收盤價、當日除權、除息、新上市、恢復交易者。',
      '外幣成交值係以本公司當日下午3時30分公告匯率換算後加入成交金額。<br>公告匯率請參考本公司首頁>產品與服務>交易系統>雙幣ETF專區>代號對應及每日公告匯率。',
    ],
    alignsStyle5: [
      ['center', 'center', 'center', 'center', 'center', 'center'],
      ['left', 'right', 'center', 'right', 'right', 'center'],
      [16, 8, 8, 4, 12, 4],
    ],
    alignsStyle8: [
      ['center', 'center', 'center'],
      ['left', 'right', 'right'],
      [16, 12, 12],
    ],
    data2: [
      [
        '臺灣生技指數',
        '4,591.55',
        "<p style ='color:green'>-</p>",
        '26.84',
        '-0.58',
        null,
      ],
      [
        '臺灣中小型公司治理指數',
        '5,307.09',
        "<p style ='color:red'>+</p>",
        '10.39',
        '0.20',
        null,
      ],
      [
        '臺灣IPO指數',
        '5,314.22',
        "<p style ='color:red'>+</p>",
        '33.01',
        '0.63',
        null,
      ],
    ],
    subtitle2: '價格指數(跨市場)',
    groups9: [
      {
        start: 0,
        span: 11,
        title: '(元,股)',
      },
      {
        start: 11,
        span: 5,
        title: '(元,交易單位)',
      },
    ],
    params: {
      response: 'json',
      type: 'ALLBUT0999',
      date: '20190904',
      controller: 'exchangeReport',
      format: null,
      action: 'MI_INDEX',
      lang: 'zh',
    },
    alignsStyle3: [
      ['center', 'center', 'center', 'center', 'center', 'center'],
      ['left', 'right', 'center', 'right', 'right', 'center'],
      [16, 8, 8, 4, 12, 4],
    ],
  };

  constructor() {}

  ngOnInit(): void {

  }

  getNumber(a:string){
    var b = Number(a);
    return b + 0;
  }
}
